version: "3.1"
services:
  qpid:
    image: damdamdeo/apache-qpid-broker-j:7.1.0
    ports:
      - 8080:8080
      - 5672:5672
#    environment:
#      - ""
    depends_on:
      - db
  db:
    image: centos/postgresql-96-centos7
    environment:
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=postgres
      -  POSTGRES_DB=postgres
